### ISSUE TITLE
[FEATURE REQUEST] Workspace/Presets support

### ISSUE THREAD

**Issue by dalisoft** [KeisukeYamashita/commitlint-rs#288]
**Describe the feature**

The **preset** feature so i could extend or add preset for linting commit in different styles like `commitlint-preset-lerna-scopes` or `commitlint-preset-angular`

## Config

-

## Error message

-

## Expected behavior

- Presets support
- Workspace support (via Preset)

## Version

```console
# Run the following command
$ commitlint --version
commitlint-rs 0.1.9
```

**Comment by KeisukeYamashita** [comment]
Great idea!
Thank you for raising this issue, I truly appreciate it. 

Basic settings could be preset, as you suggested!

However, due to time constraints and the product's immaturity, please let me think about it when the tool expands again (so let me close the Issue for now and we'll reopen it when the time is right!) Thank you again!
